services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'appdb'
    ports:
      - "1221:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - "6379:6379"
    expose:
      - 6379

  app:
    build: .
    container_name: fastapi_app
    command: ["gunicorn", "src.main:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000" 
    depends_on:
      - db
      - redis
    environment:
      # - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "src.tasks.tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "src.tasks.tasks", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  flower:
    build: .
    container_name: flower_app
    command: ["celery", "-A", "src.tasks.tasks", "flower", "--port=5555"]
    depends_on:
      - redis
      - celery_beat
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: